name: Bug Report
description: "Something's not quite right."
labels: [ "bug" ]
assignees: [ "justinhschaaf" ]
body:
  - type: textarea
    id: actual
    attributes:
      label: Summarize the issue
      description: "What's going on?"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: "What's supposed to happen?"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: "How do you make the issue occur consistently?"
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible solutions
      description: What could be changed to make this work as expected?
