[package]
name = "pigweb_server"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
pigweb_common = { path = "../common" }
serde.workspace = true
uuid.workspace = true
diesel = "2.2.5"
rocket = { version = "0.5.1", features = ["json"] }
tantivy = "0.22.0"
