[package]
name = "pigweb_server"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
pigweb_common = { path = "../common", features = ["server"] }
log.workspace = true
rocket.workspace = true
serde.workspace = true
uuid.workspace = true
diesel = "2.2.5"
figment = "*"
tantivy = "0.22.0"
