[package]
name = "pigweb_common"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
uuid.workspace = true
